travis:
  secure:
    BINSTAR_TOKEN: kGkmLVRlRzbtixZf7b2rBEOYB1m9+96nRsDBD0ay4V5fXGvxlkoeTLLj8JrI3Ji7dDWfm5kR7l82ZaMRSzidD4i0ohnPbzK3MsP/NOub2QWJnuaJqEEDJTaApF9XKLTKD2L176QYhb0xxPE0dOZc6gMIjSEAXADfNM5I18hI5W0Pq5WOgOgH+BrC5NGVxzMGKCNcky+sxNxuxUwX0b9rmLUcBfUKG2cFB9IzYFRn1SqmteEYZAUcWJ88Y7SjcLar5/kMlsNUvxsbgl2z3d4FnMowUnVXGaHSOs1qTPILGPcCcSPiyYRgd04e0PdKPBDweZTz1Oso8IKeQHIWhyIEy9sWYGlSFJJvZbmMfayZeBqJjd4FeMCWRHvqVWZtEE2keuyyC56zVTu2UOjWLq1oDsKPshK6555eIV9Z8tmAcclVKmGKX0TKrmfhmCVi+GAai70Ew5HINQuXxs14omhTdu+9cFlC8VF7peEY7I9JFVo78pRZNfIq3ZoUSKnnbuGwJjDKEZ63061SAgBuirwd6lfx9JOuQ9BVTz9ZpQ6R9/Sh6kqChmVg/FYEAghzBRpVaBCVolRiMoI+JFODVFk0eY4WpXDiDTDyQ+Z7jLw142Y9y67/xsfQ9dS0x2/HuE2emIM3eskJZRJUQCcems1uJoNzqASy9H5eJ2jilM7tcvw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
